version: "3.9"
services:
  web:
    build: ./
    pull_policy: build
    image: nextjs-static1
    restart: unless-stopped
    volumes:
      - web:/www
    ports:
      - 49365:8080

volumes:
  web:
